hello:
  defaultName: anonymous

server:
  applicationContextPath: /
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

database:
  driverClass: org.postgresql.Driver
  user: user
  password: pass
  url: jdbc:postgresql://localhost/db-local
